"""empty message

Revision ID: c8f3ea0c0c3c
Revises: 
Create Date: 2018-04-18 10:45:46.769054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f3ea0c0c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'board_id')
    # ### end Alembic commands ###
